version: '3'

services:
  python_backend:
    build: ./backend/python
    image: camptocamp/course_docker_backend:python
    volumes:
      - ./backend/python/:/usr/src/app/
      - ./backend/data.json:/etc/backend/data.json

  go_backend:
    build: ./backend/go
    image: camptocamp/course_docker_backend:go
    volumes:
      - ./backend/data.json:/etc/backend/data.json

  java_backend:
    build: ./backend/java
    image: camptocamp/course_docker_backend:java
    volumes:
      - ./backend/data.json:/var/lib/jetty/webapps/ROOT/WEB-INF/classes/data.json
      - ./backend/java/logback.xml:/var/lib/jetty/webapps/ROOT/WEB-INF/classes/logback.xml

  frontend:
    build: ./frontend
    image: camptocamp/course_docker_frontend:latest
    ports:
      - 8080:8080
    environment:
      #BACKEND_HOST: python_backend
      #BACKEND_HOST: go_backend
      BACKEND_HOST: java_backend
    volumes:
      - ./frontend:/var/www/html
